#!/usr/bin/env python3
"""
Regenerates lib/service-area-zips.ts — the list of zip codes the quiz accepts.

Source: US Census 2020 ZCTA-to-county relationship file. Each zip is assigned to
the county that holds the largest share of its land area, then kept if that
county (or state) is in REGIONS below.

To change the service area, edit REGIONS and run:
    python3 scripts/build-service-area-zips.py

Note: ZCTAs approximate USPS zip codes. PO-box-only and unique-organization zips
have no ZCTA, so they aren't included.
"""
import csv
import io
import json
import pathlib
import urllib.request
from collections import defaultdict

CENSUS_URL = (
    "https://www2.census.gov/geo/docs/maps-data/data/rel2020/zcta520/"
    "tab20_zcta520_county20_natl.txt"
)

# Each region is a list of 2-digit state FIPS prefixes (whole state) and/or
# 5-digit county FIPS codes.
REGIONS = {
    "New Jersey (entire state)": {"states": ["34"]},
    "Connecticut (entire state)": {"states": ["09"]},
    "New York City (Manhattan, Brooklyn, Queens, Bronx, Staten Island)": {
        "counties": ["36061", "36047", "36081", "36005", "36085"]
    },
    "Long Island (Nassau + Suffolk counties)": {"counties": ["36059", "36103"]},
    "Philadelphia (Philadelphia County, PA)": {"counties": ["42101"]},
    "Los Angeles (Los Angeles County, CA)": {"counties": ["06037"]},
    "Miami (Miami-Dade County, FL)": {"counties": ["12086"]},
    "Orlando (Orange County, FL)": {"counties": ["12095"]},
    "Detroit (Wayne County, MI)": {"counties": ["26163"]},
    "Dallas-Fort Worth (Dallas, Tarrant, Collin, Denton counties, TX)": {
        "counties": ["48113", "48439", "48085", "48121"]
    },
}


def main() -> None:
    raw = urllib.request.urlopen(CENSUS_URL).read().decode("utf-8-sig")
    reader = csv.DictReader(io.StringIO(raw), delimiter="|")

    # zip -> (best_land_area, county_fips)
    primary: dict[str, tuple[int, str]] = {}
    for row in reader:
        zcta = row["GEOID_ZCTA5_20"]
        if not zcta:
            continue
        land = int(row["AREALAND_PART"] or 0) or int(row["AREAWATER_PART"] or 0)
        county = row["GEOID_COUNTY_20"]
        if zcta not in primary or land > primary[zcta][0]:
            primary[zcta] = (land, county)

    by_region: dict[str, list[str]] = defaultdict(list)
    for zcta, (_, county) in primary.items():
        for name, spec in REGIONS.items():
            if county[:2] in spec.get("states", []) or county in spec.get("counties", []):
                by_region[name].append(zcta)
                break

    all_zips = sorted({z for zips in by_region.values() for z in zips})

    lines = [
        "// GENERATED by scripts/build-service-area-zips.py — do not edit by hand.",
        "// Source: US Census 2020 ZCTA-to-county relationship file.",
        "//",
        "// Regions included:",
    ]
    for name in REGIONS:
        lines.append(f"//   - {name}: {len(by_region[name])} zips")
    lines += [
        "",
        f"export const SERVICE_AREA_ZIPS: ReadonlySet<string> = new Set({json.dumps(all_zips)});",
        "",
        "/** Pulls a 5-digit zip out of user input (accepts ZIP+4 like 07030-1234). */",
        "export function extractZip(input: string): string | null {",
        "  const match = input.trim().match(/^(\\d{5})(?:-\\d{4})?$/);",
        "  return match ? match[1] : null;",
        "}",
        "",
        "export function isServiceAreaZip(input: string): boolean {",
        "  const zip = extractZip(input);",
        "  return zip !== null && SERVICE_AREA_ZIPS.has(zip);",
        "}",
        "",
    ]
    out = pathlib.Path(__file__).resolve().parent.parent / "lib" / "service-area-zips.ts"
    out.write_text("\n".join(lines))

    print(f"Wrote {out} — {len(all_zips)} zips total\n")
    for name in REGIONS:
        zips = sorted(by_region[name])
        print(f"{name}: {len(zips)} zips ({zips[0]}–{zips[-1]})" if zips else f"{name}: 0")


if __name__ == "__main__":
    main()
